epochs: 500
per_batch_size: 2
img_size: 640
iou_thres: 0.7
conf_free: True
sync_bn: True
opencv_threads_num: 0

network:
  model_name: shipwise
  nc: 28
  reg_max: 16

  stride: [ 8, 16, 32 ]

  backbone:
    - [ -1, 1, ConvNormAct, [ 64, 3, 2 ] ]
    - [ -1, 1, ConvNormAct, [ 128, 3, 2 ] ]
    - [ -1, 3, C2f, [ 128, True ] ]
    - [ -1, 1, ConvNormAct, [ 256, 3, 2 ] ]
    - [ -1, 6, C2f, [ 256, True ] ]
    - [ -1, 1, ConvNormAct, [ 512, 3, 2 ] ]
    - [ -1, 6, C2f, [ 512, True ] ]
    - [ -1, 1, ConvNormAct, [ 1024, 3, 2 ] ]
    - [ -1, 3, C2f, [ 1024, True ] ]
    - [ -1, 1, SPPF, [ 1024, 5 ] ]

  head:
    - [ -1, 1, Upsample, [ None, 2, 'nearest' ] ]
    - [ [ -1, 6 ], 1, Concat, [ 1 ] ]
    - [ -1, 3, C2f, [ 512 ] ]

    - [ -1, 1, Upsample, [ None, 2, 'nearest' ] ]
    - [ [ -1, 4 ], 1, Concat, [ 1 ] ]
    - [ -1, 3, C2f, [ 256 ] ]

    - [ -1, 1, ConvNormAct, [ 256, 3, 2 ] ]
    - [ [ -1, 12 ], 1, Concat, [ 1 ] ]
    - [ -1, 3, C2f, [ 512 ] ]

    - [ -1, 1, ConvNormAct, [ 512, 3, 2 ] ]
    - [ [ -1, 9 ], 1, Concat, [ 1 ] ]
    - [ -1, 3, C2f, [ 1024 ] ]

    - [ [ 15, 18, 21 ], 1, YOLOv8Head, [ nc, reg_max, stride ] ]
